# -*- coding: utf-8 -*-
"""standalone

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NYKHXFvSZtsb-I4ANI9I3OzzbXtQDvCV
"""

!git clone https://github.com/VyshaliEtikala/WaferAnchor.git

!ls -R WaferAnchor

!python WaferAnchor/src/generate_dataset.py

!cd WaferAnchor && git pull

!ls -l WaferAnchor/src

!python -m py_compile WaferAnchor/src/generate_dataset.py WaferAnchor/src/inference.py

from google.colab import files
uploaded=files.upload()

import zipfile

zip_path = "WaferAnchor_30_Image_Pairs.zip"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall("WaferAnchor_images")

print("Images extracted successfully! 🎉")

!find WaferAnchor_images -type f | head -20

from PIL import Image
import matplotlib.pyplot as plt
from pathlib import Path

image_dir = Path("WaferAnchor_images/generated/images")

ref = Image.open(image_dir / "ref_00000.jpg")
search = Image.open(image_dir / "search_00000.jpg")

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.imshow(ref, cmap="gray")
plt.title("Reference Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(search, cmap="gray")
plt.title("Search/Test Image")
plt.axis("off")

plt.show()

from pathlib import Path

image_dir = Path("WaferAnchor_images/generated/images")

print("Number of reference images:", len(list(image_dir.glob("ref_*.jpg"))))
print("Number of search images:", len(list(image_dir.glob("search_*.jpg"))))

import cv2
import json
import numpy as np
from pathlib import Path

image_dir = Path("WaferAnchor_images/generated/images")
metadata_path = Path("WaferAnchor_images/generated/metadata.json")

with open(metadata_path, "r") as f:
    metadata = json.load(f)

def predict_location(ref_path, search_path):
    ref = cv2.imread(str(ref_path), cv2.IMREAD_GRAYSCALE)
    search = cv2.imread(str(search_path), cv2.IMREAD_GRAYSCALE)

    # Normalize both images
    ref = cv2.GaussianBlur(ref, (3, 3), 0)
    search = cv2.GaussianBlur(search, (3, 3), 0)

    ref = cv2.normalize(ref, None, 0, 255, cv2.NORM_MINMAX)
    search = cv2.normalize(search, None, 0, 255, cv2.NORM_MINMAX)

    best_score = -1
    best_xy = None

    # Multi-scale matching
    for scale in np.linspace(0.82, 1.18, 19):
        h, w = ref.shape
        nw = max(16, int(w * scale))
        nh = max(16, int(h * scale))

        if nw >= search.shape[1] or nh >= search.shape[0]:
            continue

        template = cv2.resize(ref, (nw, nh))

        result = cv2.matchTemplate(
            search,
            template,
            cv2.TM_CCOEFF_NORMED
        )

        _, score, _, location = cv2.minMaxLoc(result)

        if score > best_score:
            best_score = score
            x, y = location
            best_xy = (
                x + nw / 2,
                y + nh / 2
            )

    return best_xy, best_score


# Test the first pair
record = metadata[0]

ref_path = Path("WaferAnchor_images/generated") / record["ref"]
search_path = Path("WaferAnchor_images/generated") / record["search"]

predicted, score = predict_location(ref_path, search_path)

ground_truth = (
    record["center"]["x"],
    record["center"]["y"]
)

error = np.sqrt(
    (predicted[0] - ground_truth[0])**2 +
    (predicted[1] - ground_truth[1])**2
)

print("PAIR 0")
print("-" * 40)
print(f"Predicted location : ({predicted[0]:.2f}, {predicted[1]:.2f})")
print(f"Ground truth       : ({ground_truth[0]:.2f}, {ground_truth[1]:.2f})")
print(f"Matching score     : {score:.4f}")
print(f"Localization error : {error:.2f} pixels")

import cv2
import json
import numpy as np
import pandas as pd
from pathlib import Path

image_base = Path("WaferAnchor_images/generated")
image_dir = image_base / "images"
metadata_path = image_base / "metadata.json"

with open(metadata_path, "r") as f:
    metadata = json.load(f)


def predict_location(ref_path, search_path):
    ref = cv2.imread(str(ref_path), cv2.IMREAD_GRAYSCALE)
    search = cv2.imread(str(search_path), cv2.IMREAD_GRAYSCALE)

    ref = cv2.GaussianBlur(ref, (3, 3), 0)
    search = cv2.GaussianBlur(search, (3, 3), 0)

    ref = cv2.normalize(ref, None, 0, 255, cv2.NORM_MINMAX)
    search = cv2.normalize(search, None, 0, 255, cv2.NORM_MINMAX)

    best_score = -1
    best_xy = None

    for scale in np.linspace(0.82, 1.18, 19):

        h, w = ref.shape
        nw = max(16, int(w * scale))
        nh = max(16, int(h * scale))

        if nw >= search.shape[1] or nh >= search.shape[0]:
            continue

        template = cv2.resize(ref, (nw, nh))

        result = cv2.matchTemplate(
            search,
            template,
            cv2.TM_CCOEFF_NORMED
        )

        _, score, _, location = cv2.minMaxLoc(result)

        if score > best_score:
            best_score = score

            x, y = location

            best_xy = (
                x + nw / 2,
                y + nh / 2
            )

    return best_xy, best_score


results = []

for i, record in enumerate(metadata):

    ref_path = image_base / record["ref"]
    search_path = image_base / record["search"]

    predicted, score = predict_location(
        ref_path,
        search_path
    )

    ground_truth = (
        record["center"]["x"],
        record["center"]["y"]
    )

    error = np.sqrt(
        (predicted[0] - ground_truth[0]) ** 2 +
        (predicted[1] - ground_truth[1]) ** 2
    )

    results.append({
        "Pair": i,
        "Predicted X": predicted[0],
        "Predicted Y": predicted[1],
        "Ground Truth X": ground_truth[0],
        "Ground Truth Y": ground_truth[1],
        "Error (pixels)": error,
        "Matching Score": score
    })


df = pd.DataFrame(results)

print("========== WAFERANCHOR EVALUATION ==========")
print(f"Number of test pairs: {len(df)}")
print(f"Average error:       {df['Error (pixels)'].mean():.2f} pixels")
print(f"Maximum error:       {df['Error (pixels)'].max():.2f} pixels")
print(f"Minimum error:       {df['Error (pixels)'].min():.2f} pixels")
print(f"Average score:       {df['Matching Score'].mean():.4f}")
print("============================================")

display(df)

!python -m pip freeze > requirements.txt

!cat requirements.txt